typedef int lexeme;

#define AUTO 1
#define DOUBLE 2
#define INT 3
#define STRUCT 4
#define BREAK 5
#define ELSE 6
#define LONG 7
#define SWITCH 8
#define CASE 9
#define ENUM 10
#define REGISTER 11
#define TYPEDEF 12
#define CHAR 13
#define EXTERN 14
#define RETURN 15
#define UNION 16
#define CONST 17
#define FLOAT 18
#define SHORT 19
#define UNSIGNED 20
#define CONTINUE 21
#define FOR 22
#define SIGNED 23
#define VOID 24
#define DEFAULT 25
#define GOTO 26
#define SIZEOF 27
#define VOLATILE 28
#define DO 29
#define IF 30
#define STATIC 31
#define WHILE 32

#define INTEGER 33
#define FLOATING_POINT 34
#define OCTAL 35
#define HEX 36
#define CHARACTER 37
#define STRING 38

#define O_SQUARE_BRAKET 39
#define C_SQUARE_BRAKET 40
#define O_BRAKET 41
#define C_BRAKET 42
#define O_CURLY_BRAKET 43
#define C_CURLY_BRAKET 44
#define COMMA 45
#define ASTERISK 46
#define TILDE 47
#define PERIOD 48

#define ARITHMETIC_OP 49
#define RELATIONAL_OP 50
#define SHIFT_OP 51
#define LOGICAL_OP 52
#define BITWISE_OP 53
#define CONDITIONAL_OP 54
#define ASSIGNMENT_OP 55
